import nodemailer from "nodemailer";
import { loadConfig } from "../utils/config.js";
import { getLogger } from "../logging/index.js";
import type { AlertEvent } from "./types.js";

const logger = getLogger().child({ component: "EmailHandler" });

interface SmtpConfig {
    host: string;
    port: number;
    user: string;
    pass: string;
    secure: boolean;
}

function resolveSmtpConfig(): SmtpConfig {
    const config = loadConfig();
    if (!config.smtpHost || !config.smtpPort || !config.smtpUser || !config.smtpPass) {
        throw new Error(
            "SMTP config missing. Set smtpHost, smtpPort, smtpUser, and smtpPass in ~/.sorokeep/config.yaml.",
        );
    }

    return {
        host: config.smtpHost,
        port: config.smtpPort,
        user: config.smtpUser,
        pass: config.smtpPass,
        secure: config.smtpPort === 465,
    };
}

function severityLabel(event: AlertEvent): string {
    if (event.type === "alert_resolved") return "Alert Resolved";
    return event.severity === "critical" ? "TTL Critical" : "TTL Warning";
}

function buildSubject(event: AlertEvent): string {
    const contractLabel = event.contractName ?? event.contractId;
    return `${severityLabel(event)} — ${contractLabel}`;
}

function buildHtmlBody(event: AlertEvent): string {
    const contractLabel = event.contractName ?? event.contractId;
    const entryLabel = event.entry.label ?? event.entry.type;
    const status = event.type === "alert_resolved" ? "Resolved" : event.severity === "critical" ? "Critical" : "Warning";

    return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>${buildSubject(event)}</title>
    <style>
      body { font-family: Arial, sans-serif; color: #111; margin: 0; padding: 0; }
      .container { padding: 24px; }
      .header { margin-bottom: 20px; }
      .badge { display: inline-block; padding: 6px 12px; border-radius: 999px; background: ${event.type === "alert_resolved" ? "#2d9f73" : event.severity === "critical" ? "#d93025" : "#f9ab00"}; color: white; font-weight: 700; }
      .section { margin-bottom: 16px; }
      .section h2 { margin: 0 0 8px 0; font-size: 18px; }
      .details { border-collapse: collapse; width: 100%; }
      .details td { padding: 8px; border: 1px solid #e1e4e8; }
      .details th { text-align: left; padding: 8px; border: 1px solid #e1e4e8; background: #f6f8fa; }
      .footer { color: #555; font-size: 13px; }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <div class="badge">${status}</div>
        <h1>${contractLabel}</h1>
      </div>
      <div class="section">
        <h2>Alert details</h2>
        <table class="details">
          <tr><th>Network</th><td>${event.network}</td></tr>
          <tr><th>Entry</th><td>${entryLabel}</td></tr>
          <tr><th>Remaining TTL</th><td>${event.threshold.currentRemainingLedgers.toLocaleString()} ledgers (${event.threshold.approximateTimeRemaining})</td></tr>
          <tr><th>Threshold</th><td>${event.threshold.configuredLedgers.toLocaleString()} ledgers</td></tr>
          <tr><th>Fired at ledger</th><td>${event.firedAtLedger.toLocaleString()}</td></tr>
          <tr><th>Timestamp</th><td>${event.timestamp}</td></tr>
        </table>
      </div>
      <div class="footer">
        <p>Delivered by Sorokeep alerting.</p>
      </div>
    </div>
  </body>
</html>`;
}

function buildTextBody(event: AlertEvent): string {
    const contractLabel = event.contractName ?? event.contractId;
    const entryLabel = event.entry.label ?? event.entry.type;
    const status = event.type === "alert_resolved" ? "Resolved" : event.severity === "critical" ? "Critical" : "Warning";

    return `${severityLabel(event)} — ${contractLabel}\n\n` +
        `Network: ${event.network}\n` +
        `Entry: ${entryLabel}\n` +
        `Remaining TTL: ${event.threshold.currentRemainingLedgers.toLocaleString()} ledgers (${event.threshold.approximateTimeRemaining})\n` +
        `Threshold: ${event.threshold.configuredLedgers.toLocaleString()} ledgers\n` +
        `Fired at ledger: ${event.firedAtLedger.toLocaleString()}\n` +
        `Timestamp: ${event.timestamp}\n\n` +
        `This alert was generated by Sorokeep.`;
}

export async function sendEmailAlert(recipient: string, event: AlertEvent): Promise<void> {
    const smtpConfig = resolveSmtpConfig();
    const transporter = nodemailer.createTransport({
        host: smtpConfig.host,
        port: smtpConfig.port,
        secure: smtpConfig.secure,
        auth: {
            user: smtpConfig.user,
            pass: smtpConfig.pass,
        },
    });

    logger.debug(`Sending email alert to ${recipient}`, { type: event.type, contractId: event.contractId });

    const mailOptions = {
        from: smtpConfig.user,
        to: recipient,
        subject: buildSubject(event),
        text: buildTextBody(event),
        html: buildHtmlBody(event),
    };

    await transporter.sendMail(mailOptions);
    logger.debug(`Email alert delivered successfully to ${recipient}`);
}
